version: '2'
services:
  telegram-bot:
    build: .
    hostname: tg-spam
    restart: always
    container_name: tg-spam

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    environment:
      - TELEGRAM_TOKEN
      - TELEGRAM_GROUP
      - DRY=true
      - DEBUG=true
    volumes:
      - ./logs:/srv/logs
      - ./html:/srv/html

    command: /srv/tg-spam --super=umputun --super=bobuk --super=grayru --super=ksenks
